title: Piráti Praha 4
administrator:
  email: tibor.vansa@gmail.com
email: tibor.vansa@gmail.com
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://praha4.pirati.cz" # the base hostname & protocol for your site

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-maps
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor

sass:
    style: compressed

permalink: /:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  projects:
    output: true
    permalink: /pripoj-se/:path/
  program:
    output: true
    permalink: /program/:path/
  elections:
    output: true
    permalink: /elections/:path/

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar: "people, foto"
  -
    scope:
      path: "_teams"
    values:
      layout: "team"
      rbar: "team-summary, teams-toc"
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar: 
      #         - garant
         - program
  -
    scope:
      path: "_elections"
    values:
      layout: "kandidatka"

calendar:
  apiKey: AIzaSyDzpWiT1UWlgmvJY1hF9Iqp3SrjPzEUHXE
  id: pirati.praha4@gmail.com
  title: "Kalendář Pirátů Praha 4"
  page: "https://calendar.google.com/calendar/embed?src=pirati.praha4%40gmail.com&ctz=Europe%2FPrague"

fb: https://www.facebook.com/PiratiPraha4/
tw:

maps:
  google:
    api_key: AIzaSyBk7Xg7HasMuCdSVKK1t7mvUiK_YwfUzWk

title-page:
  big:
    foto: /assets/img/miscellaneous/featured-nemocnice.gif
    alt: Bojueme za zachování nemocnice Na Františku
    url: https://praha.pirati.cz/tags/#nemocnice-na-františku
  left-top:
    text: Kdo jsme?
    url: https://praha.pirati.cz/lide/
    icon: fa fa-users
  right-top:
    text: Piráti ve sněmovně
    url: https://www.pirati.cz/snemovna/
    icon: fa fa-newspaper-o u-rotate-345
  left-bottom:
    text: Městské části
    url: mestske-casti
    icon: fa map-signs
  right-bottom:
    text: Připoj se
    url: pripoj-se
    icon: fa fa-bullhorn u-rotate-345

emptyArray: []
